### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by billymedia** [nystudio107/instantanalytics#10]
I have been using the plugin for a while now and today, out the blue, i get this error:
```
Internal Server Error
cURL error 6: Could not resolve host: www.google-analytics.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
Its a craft error displayed in the template. Disabling the plugin removes the error.
I have the UA code in place, i know its the current active one. Any ideas?

Craft CMS 2.6.2964
Plugin version: 1.1.5

**Comment by khalwat** [comment]
Yes, the library that InstantAnalytics uses was not properly catching this error. It happened when there were DNS issues, and it was unable to resolve `www.google-analytics.com`

It's fixed in 1.1.7, which is now released. If this error condition happens now, it will simply log the error to `craft.log`
